### ISSUE TITLE
Question: Ruby LSP VS Code extension doesn't show syntax errors; RuboCop extension does but I get duplicate linting

### ISSUE THREAD

**Issue by feliperaul** [Shopify/ruby-lsp#1002]
### Ruby version

ruby 3.2.2

### Description

Ruby LSP VS Code extension has RuboCop "built in".

However, the extension by itself doesn't show any syntax errors:

![image](https://github.com/Shopify/ruby-lsp/assets/743879/2fe3ee1b-4232-4fd7-9d74-f4d40976e112)

If I also install the [RuboCop extension](https://marketplace.visualstudio.com/items?itemName=rubocop.vscode-rubocop), then I get immensely helpful red squiggly lines like this:

![image](https://github.com/Shopify/ruby-lsp/assets/743879/bc235d34-e430-4b55-9660-a57d9ff45e2f)

However, as soon as I fix that syntax error I now have RuboCop running twice, one from the `RuboCop` extension, and the other one from what I think is the Ruby LSP built in RuboCop:

![image](https://github.com/Shopify/ruby-lsp/assets/743879/f14efdb0-dd50-466f-8321-197dc3aafebc)

Is there a way to get those syntax errors with Ruby LSP alone? 

If not (and I must install RuboCop alongside it), any way to disable the RuboCop linting inside the Ruby LSP so I don't get duplicate linting?

### Expected output

(As described above)

**Comment by vinistock** [comment]
> However, the extension by itself doesn't show any syntax errors:

This is an intentional decision from the Ruby LSP. Running RuboCop diagnostics is very slow on larger files and so we try to minimize the amount of times we need to run it.

We will show syntax errors by default when we finish migrating to the new parser (YARP) on #449 - which should hopefully be completed very soon.

> any way to disable the RuboCop linting inside the Ruby LSP so I don't get duplicate linting?

Yes, you can enable or disable features in the Ruby LSP. See the [extension documentation](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#configuration) on how to configure it.
