### ISSUE TITLE
Function parentheses completion

### ISSUE THREAD

**Issue by kuator** [Shopify/ruby-lsp#1193]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

Convenience

### Description

typescript-language-server has this nice feature where it autocompletes braces and arguments for a function.
Here's a demonstration:

![Peek 2023-11-20 15-56](https://github.com/Shopify/ruby-lsp/assets/25168308/0696aed2-3b80-4a06-99dd-99d7818cc338)

**Comment by vinistock** [comment]
The reason is because we have full support for methods yet. Version v0.12.4 (released today) has early support only for methods invoked directly on `self`.

The rest of the work is tracked in #899, so I'll close this one to centralize discussions.

I also wanna mention one thing: TypeScript has fully accurate features like go to definition, hover and completion because of the type annotations, which assist the typechecker in figuring out exactly what methods you are looking for.

Without any typing system, there will always be cases where results are not accurate for Ruby. The most common example being when the LSP does not know the type of a method receiver

```ruby
# If you want to jump to the definition of `bar` or get completion after `foo`
# We need to know the type of `foo`. It's usually not possible to do this in a performant
# way without type annotations and a proper typechecker
foo.bar
```

All that is to say, if you're looking for a TypeScript-like experience you may want to consider adopting typing through Sorbet or Steep in your project.
