### ISSUE TITLE
Nested definitions and references should take parent module(s) into consideration

### ISSUE THREAD

**Issue by danielolivaresd** [Shopify/ruby-lsp#1268]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

It's important to find the external references of a class when using the recommended [namespace definition](https://rubystyle.guide/#namespace-definition) syntax (e.g. `Module A; class B` instead of `Class A::B`). The alternative to this is manually searching it in the codebase.

### Description

Consider the following use case in which we have two files:

```ruby
# something/foo.rb
module Something
  class Foo
    Bar.new # This is Line 3
  end
end

# something/bar.rb
module Something
  class Bar
  end
end
```

If I `cmd` + `click` `Bar` in L3 of `something/foo.rb`, I get a popover/alert saying `"No references found for 'Bar'"`. It looks like the definition of the class does not take its parent module(s) into account. To find references, I need to declare `Something::Bar.new` instead, which is a bit of a hassle, considering we're already in the same module `Something`.

**Comment by danielolivaresd** [comment]
Please let me know if I'm missing something (e.g. if this is something that is already implemented but needs to be configured), or if this is something specific to VSCode and I need to move it to the other repo.

**Comment by vinistock** [comment]
Oh, I see what you mean now. Sorry, I had misunderstood what you meant.

Showing references is a separate feature independent from go to definition. We just haven't implemented it yet https://github.com/Shopify/ruby-lsp/issues/202.

We are investigating some performance improvements for the indexing mechanism so that we can start keeping track of all references, which unblocks both finding references and renaming.

I'll close this issue given that we already have #202 to track it.
