### ISSUE TITLE
Unexpected $0 after do keyword

### ISSUE THREAD

**Issue by goofansu** [Shopify/ruby-lsp#1269]
### Ruby version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

### Code snippet

```
each do |
```

It seems the related code is: https://github.com/Shopify/ruby-lsp/blob/fa551180d8be4e9e8e439f98c44a894de09df6c9/lib/ruby_lsp/requests/on_type_formatting.rb#L159-L175

After above input, it becomes:
```
each do ||$0
```

### Description

I'm using Emacs and the built-in Eglot to apply ruby-lsp for Ruby projects.

Emacs version: 29.1
ruby-lsp version: 0.13.0

Please see the screencasts: 
https://github.com/Shopify/ruby-lsp/assets/1143191/3cbbdc71-2429-4e3a-9e79-b736ff55a0cb
https://github.com/Shopify/ruby-lsp/assets/1143191/be3f5576-12e8-4162-9ade-87df63fc8299

The problem is not limited to `each do` block, any `do` blocks have the problem.

### Expected output

```
each do |<cursor here>|
end
```

**Comment by vinistock** [comment]
Thank you for the bug report! The `$0` is a [VS Code snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets) that allows changing the position of the cursor after applying the on type formatting completion. By default, editors always end up with the cursor at the last character of the completion, so we use that to move the editor back into where the user would likely be typing next.

Do you know if Emacs/Eglot has support for snippets that do the same?

I suspect the fix is going to not using snippets if the editor connecting to the server is not VS Code, but if other editors also support snippets maybe we can improve the experience further.

FWIW, I should also mention that the specification is going to get snippet support baked-in [soon](https://github.com/microsoft/language-server-protocol/issues/724). So it's likely that editors will need to implement support for them if they don't already have it.

**Comment by goofansu** [comment]
@vinistock Here are the event logs of Eglot when I finished to type `do |`:

```
[client-request] (id:61) Sat Jan  6 09:55:52 2024:
(:jsonrpc "2.0" :id 61 :method "textDocument/onTypeFormatting" :params
          (:textDocument
           (:uri "file:///Users/james/work/myproj/demo.rb")
           :options
           (:tabSize 8 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t)
           :position
           (:line 0 :character 4)
           :ch "|"))
[server-reply] (id:61) Sat Jan  6 09:55:52 2024:
(:id 61 :result
     [(:range
       (:start
        (:line 0 :character 4)
        :end
        (:line 0 :character 4))
       :newText "|")
      (:range
       (:start
        (:line 0 :character 4)
        :end
        (:line 0 :character 4))
       :newText "$0")]
     :jsonrpc "2.0")
```

`ruby-lsp` replied to insert `|` and `$0` in the `textDocument/onTypeFormatting` event, causing the text becomes `do ||$0`. There is no snippet expanding in this event in Eglot (according to https://github.com/joaotavora/eglot/discussions/1347#discussioncomment-8001753).

The full event logs: https://gist.github.com/goofansu/ff055cc58f853856101ac7183d67bf8c
