### ISSUE TITLE
Handle same method name in multiple files

### ISSUE THREAD

**Issue by gottlike** [Shopify/ruby-lsp#1343]
### Ruby version

3.2.2

### Description

In a project I have multiple folders with basically the same functionality (very modular), so I could have `def do_something` in `folder-one/script.rb` and `folder-two/script.rb`. However, the method description could differ.

Currently Ruby LSP doesn't necessarily display the description of the current one on hover. Also when clicking, it might open another file.

### Expected output

I would expect Ruby LSP to show/use the method definition of the current file only, when there's duplicate methods in the project.

**Comment by gottlike** [comment]
Thanks for your reply. Sure, here is a simple example:

`test1.rb`
```ruby
# frozen_string_literal: true

module Func
  def start
    something('great')
  end

  # Does something interesting
  def something(input)
    puts input
  rescue StandardError => e
    raise("#{name}.#{__method__} > #{e.message}")
  end
end
```

`test2.rb`
```ruby
# frozen_string_literal: true

module Func
  # Does something else entirely
  def something(input)
    puts input
  rescue StandardError => e
    raise("#{name}.#{__method__} > #{e.message}")
  end
end
```

![image](https://github.com/Shopify/ruby-lsp/assets/278766/663bb675-6295-415f-9a7d-fd86e396ef5f)

**Comment by vinistock** [comment]
Thank you for the context, I understand the problem now.

There's indeed a bug there, we should be concatenating the documentation for all definitions of `Fun#something`, since it's being overridden in multiple places.

However, notice that the declarations are not considered file specific. All declarations inside the same workspace are indexed and will show up in the editor.

**Comment by gottlike** [comment]
Well, if both are shown, that's still fine, I guess :). Thanks!
