### ISSUE TITLE
Add support for syntax_tree plugins

### ISSUE THREAD

**Issue by h14h** [Shopify/ruby-lsp#1461]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

My primary use-case would be to leverage the [`syntax_tree-erb`](https://github.com/davidwessman/syntax_tree-erb/tree/main) plugin to enable using Ruby LSP and syntax tree as my formatter for erb files, as well as ruby files.

Other use-cases would involve using other syntax_tree plugins, be they official, community-driven, or custom to my project.

### Description

I propose passing `plugins` options to the syntax tree formatting runner:

https://github.com/Shopify/ruby-lsp/blob/d1da8858a146d5c600af3371e37a960961080858/lib/ruby_lsp/requests/support/syntax_tree_formatting_runner.rb#L40

...to ensure that Ruby LSP passes along any plugins specified in my [syntax tree config](https://github.com/ruby-syntax-tree/syntax_tree?tab=readme-ov-file#configuration) to the syntax tree formatter.

**Comment by vinistock** [comment]
Thank you for the feature suggestion! I believe this issue is more related to the fact that we don't yet [handle ERB files](https://github.com/Shopify/ruby-lsp/issues/1055), rather than loading Syntax Tree plugins. I assume that, as long as we load the Syntax Tree configuration (which we do), the plugins should already work out of the box.

But you won't get any features (not just formatting) for ERB files until the LSP has support for them.

**Comment by h14h** [comment]
Ah thank you for clarifying! I'll close this out then, as the core use-case (formatting ERB files) would require the issue you linked to.

Looking forward to future Ruby LSP features! Hopefully we're not far from a future where we have a single "default" tool for providing IDE-like features to both Ruby & ERB 🙂
