### ISSUE TITLE
Add go to definition support for autoloaded constants

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1893]
Basically, the same feature as go to definition for [require](https://github.com/Shopify/ruby-lsp/blob/ee5f44d316de3e3f13163344e7a3b8c65c2d9429/lib/ruby_lsp/listeners/definition.rb#L91), but in this case for autoloads.

```ruby
module Foo
  autoload :Bar, "bar" # <- jumping to bar should take you to the right file
end
```

We can probably add the same for the constant too, since we know that it must resolve to `Foo::Bar`, which makes it easy to search in the index.

**Comment by Super-Xray** [comment]
Hi, @vinistock I'm interested in this feature, can I handle this issue?

**Comment by Super-Xray** [comment]
Hello @vinistock , I'm interested in this issue, can I handle it?

**Comment by Super-Xray** [comment]
Thank you very much! Since this is my first OSS contribution, I didb't know this before.

**Comment by Super-Xray** [comment]
However，I have found that the structure of autoload statement is 
![image](https://github.com/Shopify/ruby-lsp/assets/110341228/df209f73-6ab6-42b0-b61f-9ae96a60c4b9)
there aren't any `ConstantNode` here so I think it's difficult to use find_in_index straightly (becuase `constant_name` method requires `ConstantPathNode`/`ConstantReadNode`/`ConstantTargetNode` input). 
In order to find the correct line, I think maybe we can refer to the mechanism of searching class or method in a file (input '@' + class_name/method name) because we can get the class's name from `SymbolNode`. Does this idea work？

**Comment by vinistock** [comment]
The `find_in_index` method accepts the name of the constant you're looking for as a string and already takes care of the namespacing for you.

For example

```ruby
module Foo
  autoload :Bar, "some/file"
end
```

In this case, you need to invoke `find_in_index` with the name `Bar` and the existing functionality will automatically discover that the referenced constant is actually `Foo::Bar`. Basically, what you need to do is extract the name from the `autoload` arguments and pass that name to `find_in_index`.

This will already make the LSP jump to the exact location where that constant is defined. You won't need the `@` based search (document symbol), to land on the right place in the file.
