### ISSUE TITLE
Bump prism version

### ISSUE THREAD

**Issue by langalex** [Shopify/ruby-lsp#1906]
Prism 0.25 fixes an [issue](https://github.com/ruby/prism/issues/2674) with its rbi files (Sorbet type definitions). Without this fix, ruby-lsp is unusable in projects using Sorbet.

ruby-lsp currently depends on prism `(>= 0.22.0, < 0.25`. Please change to  `< 0.26` or similar.

**Comment by vinistock** [comment]
Thanks for the report!

> ruby-lsp is unusable in projects using Sorbet

Not sure how this is the case. We use Ruby LSP with Sorbet in all our projects. Is this more related to not using Tapioca?

Also, do you have `ruby-lsp` added to your Gemfile? It shouldn't be necessary to add it to the Gemfile since version `v0.8.0`.

Regardless, we always keep up to date with Prism updates, so we'll be updating soon.
