### ISSUE TITLE
Issues with rbenv and git sources

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#1947]
### Reproduction steps

I have a git gem in my gemfile, during booting the ruby-lsp seems to instruct bundler to look into the wrong spot for that.

> The path `/home/user/.local/share/gem/ruby/3.2.0/bundler/gems/gem_name-5ef8fd7a5205` does not exist. (Bundler::PathError)

`/home/user/.local/gem` does in fact not exist on my machine. The correct path would be `/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/gem_name-5ef8fd7a5205/`. With `bundle exec irb` I am able to correctly require and use the gem.

Here's the relevant part of the activation script:

```rb
{:env=>
  {:SHELL=>"/bin/bash",
   :RBENV_HOOK_PATH=>
    "/home/user/.rbenv/rbenv.d:/usr/lib/rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks",
   :RBENV_SHELL=>"bash",
   :PWD=>"/home/user/Documents/project",
   :HOME=>"/home/user",
   :RBENV_ORIG_PATH=>
    "/home/user/.rbenv/shims:/home/user/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/.local/bin:/home/user/.local/bin",
   :USER=>"user",
   :RBENV_DIR=>"/home/user/Documents/project",
   :RBENV_VERSION=>"3.2.2",
   :PATH=>
    "/home/user/.rbenv/versions/3.2.2/bin:/usr/lib/rbenv/libexec:/home/user/.rbenv/shims:/home/user/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/.local/bin:/home/user/.local/bin",
   :RBENV_ROOT=>"/home/user/.rbenv"},
 :yjit=>true,
 :version=>"3.2.2",
 :home=>"/home/user/.local/share/gem/ruby/3.2.0",
 :default=>"/home/user/.rbenv/versions/3.2.2"}
```

If I revert #1811 it works again. Perhaps it needs to check for the presence of `Gem.user_dir` before adding it to the env?

**Comment by vinistock** [comment]
Thank you for reporting this. I might have misunderstood exactly how rbenv sets up gem environment variables.

Can you please print these in your terminal (with rbenv activated)? I'm trying to understand if rbenv is setting the environment variables or if relies on Ruby's defaults.

```shell
echo $GEM_HOME
echo $GEM_PATH
echo $PATH
```

For the `PATH`, what I need to know is: does rbenv add gem bin directories to the path? Or does it add some `shims` directory into the path?

For example, chruby adds directories like `~/.gem/ruby/3.2.2/bin` to the `PATH`, so that you can invoke gem executables. Asdf on the other hand, doesn't add those and instead adds its shims directory to the `PATH`, where they have a shim for every gem executable (`~/.asdf/shims`).

**Comment by Earlopain** [comment]
Now that's a quick turnaround! With the extension from that PR the LSP is able to again start up without errors in the project that contains the git source. This is great, thank you.
