### ISSUE TITLE
Metadata for VSCode extensions still points to `vscode-ruby-lsp`

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#1970]
### Description

https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp

![grafik](https://github.com/Shopify/ruby-lsp/assets/14981592/102c2420-517f-4f3e-9bb5-53cbbeeeb0d8)

Same for the issues/repository/etc. links.

I think it's also showing a version number from the server?

**Comment by vinistock** [comment]
Thanks for the report. This is because we have prerelease version published of the extension with a higher version number than the stable release. The marketplace always favours the highest version number and that one was published from the old repo.

Once https://github.com/Shopify/ruby-lsp/pull/1967 is merged, we will have stabilized all of the prerelease behaviour and can finally release `v0.7.0`, which will then fix the data in the marketplace.
