### ISSUE TITLE
Failed to activate asdf environment

### ISSUE THREAD

**Issue by davijonm** [Shopify/ruby-lsp#1999]
Vscode, asdf and Ruby LSP are all in the latest versions

1. Start the Ruby LSP using vs code
2. Open a Ruby file
3. Try to Ruby LSP: Start
4. Shows the error ailed to activate asdf environment: Unexpected token '/', "/bin/sh: 2"... is not valid JSON
![Screenshot from 2024-05-01 13-17-02](https://github.com/Shopify/ruby-lsp/assets/95036138/9cd85e15-f4d4-4ea1-966a-4e998dff8465)
![Screenshot from 2024-05-01 13-19-16](https://github.com/Shopify/ruby-lsp/assets/95036138/49d9831b-4a4f-498b-8db0-ebb10f8a422f)

**Code snippet or error message**
VS code message: Failed to activate asdf environment: Unexpected token '/', "/bin/sh: 2"... is not valid JSON

**Comment by andyw8** [comment]
:wave: This seems like the same issue as https://github.com/Shopify/ruby-lsp/issues/1990 which was solved by updating `asdf`. What version of `asdf` is in use?

**Comment by andyw8** [comment]
Thanks. And how was `asdf` installed?

**Comment by vinistock** [comment]
Based on what I could gather, it seems that `/bin/sh` (the default shell used when calling `exec`) doesn't support the `[[ ]]` syntax on all operating systems. I assume you're using some other shell in your terminal and not `/bin/sh`, otherwise you'd see the problem there as well.

I think we can try to run exec with the shell identified by VS Code, which I'm exploring on this PR https://github.com/Shopify/ruby-lsp/pull/2006.

@davijonm it would be extremely helpful if you could confirm that this fixes the issue. You can do so by following these steps:

1. Clone the project
2. Switch to the branch in the PR or apply the changes manually (since it's only a few changes)
3. Install dependencies (`cd vscode && yarn install`)
4. Open our custom workspace by clicking on the [workspace file](https://github.com/Shopify/ruby-lsp/blob/main/lsp.code-workspace) and then click the button open workspace
5. In the `Run and debug` panel, select the task `Run extension` and click start. This will open a second VS Code window where the development version of the extension is running
6. In the second window, did the Ruby LSP launch properly with the changes in the branch?

**Comment by davijonm** [comment]
Ok, did all the steps. In the step 5, it opened a second window with this error bellow:
![Screenshot from 2024-05-02 20-26-25](https://github.com/Shopify/ruby-lsp/assets/95036138/db9e7794-d117-4eef-a38a-06a1d2ea6b62)

**Comment by davijonm** [comment]
I use zsh but asdf is set in both .zshrc and .bashrc files

**Comment by vinistock** [comment]
Not sure why it still used `/bin/sh`. I pushed https://github.com/Shopify/ruby-lsp/pull/2006 to fallback to `process.env.SHELL` and added a print so that we can inspect the values. If you don't mind giving it another try, I'd like to understand if `vscode.env.shell` is not set for you.

**Comment by davijonm** [comment]
Here is the result
![Screenshot from 2024-05-03 17-43-50](https://github.com/Shopify/ruby-lsp/assets/95036138/a5bd13c5-64d1-4f69-92b9-d86e7c6a9ea1)

**Comment by davijonm** [comment]
Hey guys, any updates?

**Comment by andyw8** [comment]
@davijonm we're still investigating. For now, you can downgrade to v0.5.19 of the extension to switch to the older activation approach.

**Comment by vinistock** [comment]
I just realized I made a mistake in the previous iteration of https://github.com/Shopify/ruby-lsp/pull/2006. I set the `shell` inside `env`, which isn't what I meant to do. I updated the branch to set the actual shell to `vscode.env.shell`.

Could you please try again and report if that fixes it?

**Comment by davijonm** [comment]
Then, in this new window, I opened a Ruby repository. In the output console, there were these messages:

![Screenshot from 2024-05-28 09-10-37](https://github.com/Shopify/ruby-lsp/assets/95036138/2aa66a9d-0a39-4bdc-bc42-b503a89241a8)
