### ISSUE TITLE
chruby integration can't find default ~/.rubies

### ISSUE THREAD

**Issue by HoneyryderChuck** [Shopify/ruby-lsp#2134]
### Reproduction steps

Hi. I have a project with no `.ruby-version`, and chruby installed. i usually select the ruby by selecting the ruby manually in cli, `chruby 3.3` for example, then `code .`.

When i do so, I get the error below. It seems ruby-lsp is assuming a default `/opt/rubies` as install location, but in my case (perhaps because I installed `chruby` and `ruby-install` as non-root) rubies are installed by default under `~/.rubies` (in mac that's even more annoying, because if I "select ruby manually" button as per screenshot, i can't see hidden dirs).

Besides the default needing some work, it'd be great to set the location of rubies as a setting, if that makes sense.

<img width="450" alt="Captura de ecrã 2024-06-05, às 18 25 53" src="https://github.com/Shopify/ruby-lsp/assets/215707/d06a859f-6901-4dc9-bca1-b364d706a961">

**Comment by HoneyryderChuck** [comment]
> If we were to fallback to None, that would risk selecting the system Ruby on MacOS or Linux,

That makes sense 👍 

> we mention that to the user and provide the option to manually select their Ruby

The confusing part here is the "manually selecting". At this point, this extension knows that I have chruby but no .ruby-version, so I'd expect it to present me with the ruby options known to chruby (select box?). Perhaps this is not really actionable, in which case ruby-lsp already does the best it can.

> Usage of chruby is more common with a .ruby-version file, which is gradually becoming the community standard for declaring the Ruby version to be used.

For applications perhaps, but not necessarily libraries supporting multiple versions, which is my use case. However, I understand you prioritizing it, there are more applications than libraries 👍

**Comment by vinistock** [comment]
> so I'd expect it to present me with the ruby options known to chruby

This would be a great improvement to the experience. Up until now, we've been focusing on getting the basics of version manager integrations right. We had multiple issues in the past related to shells, which we have addressed.

Since we support rbenv, chruby, rvm, asdf, mise, shadowenv, none (no version manager) and custom (a custom shell script that selects Ruby), we haven't prioritized any sort of extra conveniences.

However, I do believe we are at a point where we can slowly start adding improvements. Showing the available rubies, like you mentioned, would be a great addition. Detecting that the Ruby configured for the current project is not install and offering to install it would be another. There's a lot that can be done, but these things are lower priority when compared to improving features or expanding capabilities.
