### ISSUE TITLE
Automatic Ruby environment activation with asdf failed

### ISSUE THREAD

**Issue by swanson** [Shopify/ruby-lsp#2137]
### Description

Ruby LSP v0.7.2
VS Code 1.90.0

Error message

```
Automatic Ruby environment activation with asdf failed: Unexpected token '/', "/opt/homeb"... is not valid JSON
```
(Cant seem to get the full text of the error?)

In my project:
```
❯ asdf current
nodejs          20.10.0         /Users/matt/.tool-versions
ruby            3.3.0           /Users/matt/dev/foo/.tool-versions

❯ ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin21]
```

My shell is zsh

```
> cat ~/.zshrc
source ~/zsh-repos/zsh-snap/znap.zsh

znap prompt sindresorhus/pure

znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-completions

znap source asdf-vm/asdf asdf.sh

fpath+=(
    ~[asdf-vm/asdf]/completions
    ~[asdf-community/asdf-direnv]/completions
    ~[zsh-users/zsh-completions]/src
)
```

**Comment by swanson** [comment]
I see this issue https://github.com/Shopify/ruby-lsp/issues/1985 but have run `asdf update`

ASDF VERSION:
v0.14.0-ccdd47d

and still having the same result

**Comment by TamsilAmani** [comment]
@vinistock 
I was facing the same problem and tried all the solutions mentioned in this issue as well as others like `upgrading asdf`, adding `/opt/homebrew/opt/asdf/libexec/lib/asdf.sh` to `.zshrc`, etc. None of them worked.

The output tab showed the error:

> Tried parsing invalid JSON environment: /Users/tamsil/.asdf/asdf.sh:.:35: no such file or directory: /opt/homebrew/opt/asdf/libexec/lib/asdf.sh

I checked and found that the correct path to `asdf.sh` is `/opt/homebrew/opt/asdf/libexec/asdf.sh` [**not libexec/lib**]

My solution:
I edited the file `/Users/tamsil/.asdf/asdf.sh`.
There was code in this script which pointed to the wrong location.

```shell
# shellcheck source=lib/asdf.sh
# Load the asdf wrapper function
. "${ASDF_DIR}/lib/asdf.sh"
``` 
I removed the "`/lib`" path from `. "${ASDF_DIR}/lib/asdf.sh"` and Ruby-LSP started working. 

I think this issue is on `asdf` and not the user. Correct me if I'm wrong.

**Comment by vinistock** [comment]
@TamsilAmani I don't understand. We don't search for the ASDF script in `/opt/homebrew/opt/asdf/libexec/lib/asdf.sh`, we search for it in `/opt/homebrew/opt/asdf/libexec/asdf.sh` ([code](https://github.com/Shopify/ruby-lsp/blob/e7f54ad7da01b4f9a0a54399d37c8fd15875b4a1/vscode/src/ruby/asdf.ts#L46)).

Are you on the latest version of the VS Code extension?

**Comment by vinistock** [comment]
@LucasKuhn the issue you described is #2878. We're not yet searching for Mise under the Homebrew installation path.

And the solution, for now, is to add this setting to point the Ruby LSP to the right Mise executable:

```jsonc
"rubyLsp.rubyVersionManager": {
  "identifier": "mise",
  "miseExecutablePath": "/opt/homebrew/bin/mise"
}
```

No need to create symlinks.
