### ISSUE TITLE
Accept declarative test syntax for minitest

### ISSUE THREAD

**Issue by ianks** [Shopify/ruby-lsp#2176]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

We have an app (storefront renderer) which uses minitest outside of Rails with custom `test do ... end` syntax, and would like to have the `Run test` code lens.

<img width="270" alt="image" src="https://github.com/Shopify/ruby-lsp/assets/3303032/5396c23e-8ff6-4362-8aee-ea00d85ccd63">

### Description

Add code lens for individual test case without rails.

**Comment by vinistock** [comment]
Thank you for the feature suggestion!

Do the tests inherit from `ActiveSupport::TestCase`? If that's the case, then https://github.com/Shopify/ruby-lsp/issues/1334 is the solution and we can close this one.

**Comment by ianks** [comment]
Unfortunately it does not, although maybe it could but it would be some work. Here's what the class looks like:

```ruby
module StorefrontRenderer
  class TestCase < Minitest::Test
    # ...
  end
end
```

**Comment by vinistock** [comment]
Minitest doesn't support the declarative syntax out of the box, so it would be a bit odd to pretend that it does and show the code lens anyway.

I believe there is a specific solution for your use case and a more general solution for any other type of custom syntax:

1. SFR should just use `ActiveSupport::TestCase` or at least `ActiveSupport::Testing::Declarative` and then #1334 will fix this and allow the correct behaviour
2. For any other arbitrary custom syntax people decide to create, we should allow applications to define their own private [addons](https://github.com/Shopify/ruby-lsp/blob/main/ADDONS.md), which is a way to extend the Ruby LSP's functionality. For example, [RSpec support](https://github.com/st0012/ruby-lsp-rspec) is implemented that way. Currently, we only allow for gems to export addons, but the change to allow for application addons should be straight forward

I'll close this issue so that we can centralize any discussions on #1334.
