### ISSUE TITLE
RubyLSP recieves requests for "fake" sorbet rbi files

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#2384]
### Reproduction steps

* Create a new `typed: true` ruby file in a project that uses sorbet.
* Have the vscode sorbet extension installed
* Type `TRUE` and press `F12` to move to its definition
* Open the extension output terminal and observe the error

```
024-07-30 12:24:35.677 [info] (ruby-lsp) [Error - 12:24:35 PM] Request textDocument/semanticTokens/range failed.
2024-07-30 12:24:35.677 [info] (ruby-lsp)   Message: /home/user/code/ruby-lsp/lib/ruby_lsp/store.rb:44:in `get': sorbet:https%3A//github.com/sorbet/sorbet/tree/090ed6096a83dd7a5fe52bd3f9338c1eca5178eb/rbi/core/constants.rbi (RubyLsp::Store::NonExistingDocumentError)
	from /home/user/code/ruby-lsp/lib/ruby_lsp/server.rb:393:in `text_document_semantic_tokens_range'
	from /home/user/code/ruby-lsp/lib/ruby_lsp/server.rb:46:in `process_message'
	from /home/user/code/ruby-lsp/lib/ruby_lsp/base_server.rb:128:in `block in new_worker'

  Code: -32602
```

Notice the uri: `sorbet:https%3A//github.com/sorbet/sorbet/tree/090ed6096a83dd7a5fe52bd3f9338c1eca5178eb/rbi/core/constants.rbi`

The location doesn't actually exist and is probably provided on-demand by the sorbet extension yet `ruby-lsp` still tries to look it up in its index.

I don't notice anything else wrong except for the error happening. Don't think there is user impact but something unexpected is happening.

**Comment by andyw8** [comment]
Thanks, I can reproduce.

**Comment by vinistock** [comment]
> We can probably fix this by returning early if uri.scheme != 'file'.

If possible, I would avoid restricting the scheme. For example, when you are using VS Code's diff editor, the files being compared do not use the `file` scheme, but the `git` one. Providing proper highlighting, hover and go to definition on that scheme is nice because it makes reviewing diffs a bit more complete.

It's hard to anticipate what other schemes will be used. As another example, maybe code blocks inside Copilot chat windows will have their own URI scheme too and we would like to provide features there. While I'm not sure if the VS Code team is looking into this, it would further integrate the LLM experience to language server features.

My suggestion is to suppress any output related to this error since it's expected to happen on certain scenarios.
