### ISSUE TITLE
Possible Bundler lock problem

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#2387]
A couple of times recently, running `bundle` on the command line has been hanging for me.

I spotted notices [this](https://github.com/rubygems/rubygems/issues/7732) issue, and found that killing off all the active Ruby processes on my machine solved the problem, so it seems something was indeed locking the update.

When it happens again, I can investigate more to try find the culprit.

cc @bdewater

**Comment by andyw8** [comment]
Interesting. I wonder if we should detect if there's a bisect in progress, and avoid running Bundler if so.

**Comment by vinistock** [comment]
If the Ruby LSP is already running bundle install, it indeed makes it impossible to run another bundle install process in the command line due to the lock. Honestly, I think that's the right behaviour since we wouldn't want two processes trying to compile and install the same gems.

That said, we should improve the Ruby LSP's bundle install reporting so that instead of just printing to STDERR, we show a progress notification (similar to indexing) with the current state of bundle install.

**Comment by Earlopain** [comment]
A progress notification like that would be pretty nice to show whats going on a bit more prominently. It makes sense for bundler to not trip over itself but having to wait a minute for gems to finish compiling (gemfile specific of course) before you can continue bisecting is :neutral_face:
