### ISSUE TITLE
"Jump to factory" link in tests

### ISSUE THREAD

**Issue by glaucocustodio** [Shopify/ruby-lsp#2417]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

Would be nice to have a "Jump to factory" link in test files similar to the "Jump to view" we have in controllers.

```ruby
describe "#foo" do
  it "calls foo" do
    # "Jump to factory" link  would appear here, once clicked would open the Widget factory
    widget = create(:widget)
    widget.foo
  end
end
```

Ps:  considering one is using the factory_bot gem

### Description

This would increase the productive of devs since they no longer will need to hit cmd+P to look for the factory file definition

**Comment by st0012** [comment]
Because this feature will require `factory_bot`-specific knowledge, which is not a Ruby default tool, it should be provided through an [addon](https://github.com/Shopify/ruby-lsp/blob/main/ADDONS.md) instead. We will not provide this feature directly from `ruby-lsp`.

You can either build a standalone addon gem like [ruby-lsp-rspec](https://github.com/st0012/ruby-lsp-rspec), or convince `factory_bot` to have a built-in addon like [standardrb does](https://justin.searls.co/posts/why-i-just-uninstalled-my-own-vs-code-extension/).

**Comment by glaucocustodio** [comment]
thank you for the references, that makes sense!
