### ISSUE TITLE
Add Addon support for inline hints

### ISSUE THREAD

**Issue by domingo2000** [Shopify/ruby-lsp#2485]
### I have checked that this feature is not already implemented

- [x] This feature does not exist

### Use case

The inlay hints are a very useful feature for displaying aditional information of the code that can be infered statically.  Currently we want to make a I18n (internationalization) addon to make an inlay hint that shows the translation beside a translation call.

For example:
```ruby
def foo
   # hints: "Hello world!" in the editor, 
   # and on hover show a tooltip that shows additional informatión about that translation.
   I18n.t("hello.world") 
```

Currently there is support for addons for other parts of the LSP standard like `CodeLens`, or `Hover` requests but not `InlayHints` so we have to override the LSP `RubyLsp::Requests::InlayHints` to get the desired behaviour for the i18n addon.

Other cases for different derived information could be shown in the editor for different project standards.

### Description

The feature will then open as the other `RubyLsp::Requests` clases open the InlayHint LSP request to Addons, to support the extension to listen those requests by simply writing an addon that register InlayHint listeners.

### Implementation

The implementation is the same as other Requests of the standard that supports addons. Just add an iteration on the addons to call the listeners.

```ruby
module RubyLsp
   class Addon
      ...
      def create_inlay_hints_listener(response_builder, range, hints_configuration, dispatcher); end
      ...
   end
end
```

In the InlayHint request iterate over the addons to call the methods implemented

```ruby
module RubyLsp
  module Requests
    class InlayHints < Request
      def initialize(...)
         ...
         Addon.addons.each do |addon|
          addon.create_inlay_hints_listener(@response_builder, start_line..end_line, hints_configuration, dispatcher)
        end
      end
   end
end
```

So each addon can create and use their `InlayHints` listeners.

Im willing to make a PR that implement this extension support.

**Comment by vinistock** [comment]
Thank you for the feature suggestion!

The team got together to discuss this. We are open to considering allowing addons to enhance inlay hints, but it depends on the use case. When we added some new inlay hints a while back, we received quite strong feedback from the community complaining that they should be turned off by default because they can be distracting.

In this particular example of I18n, the team agreed that constantly showing the information as inlay hints wouldn't be a nice experience. A developer doesn't need to see the translation contents at all times while they are working, so having this constantly visible would likely degrade the experience.

For this specific feature, we recommend showing the content when hovering over the translation key in the I18n invocation:

```ruby
I18n.t("blah.blah")
#       ^ hovering here would show the contents of blah.blah
```

We'd be happy to accept this as a contribution to the [Rails addon](https://github.com/Shopify/ruby-lsp-rails) if you want to contribute that.

If you have other examples where you believe inlay hint would be the right fit, please let us know and we can re-consider.
