### ISSUE TITLE
Reduce noise from "This file is too long" warning.

### ISSUE THREAD

**Issue by ksweetie** [Shopify/ruby-lsp#2550]
### I have checked that this feature is not already implemented

- [x] This feature does not exist

### Use case

We have several large files that I end up opening frequently. I've been closing the notification popup probably a dozen~ times a day, which can get pretty frustrating when it keeps happening.

![Image](https://github.com/user-attachments/assets/85a3673c-dfc6-4e19-89aa-c2e4715be8e2)

I know I could refactor these large files into smaller ones, but they're pretty long for a reason, and I'm not sure how I'd easily break them apart.

### Description

I'm not sure what the best fix would be. Here are some ideas, but my guess is that you all will probably be able to think of something better.

1. A way to disable the warning.
2. Only warn for a file once, not every time you open the file.
3. A file ignore list.
4. Send the warning to a less intrusive place (I think there's a difference between notification panels and popups, but I don't know how that works).
5. Remove the warning entirely.

**Comment by ksweetie** [comment]
One other note: Zed editor has a concept of [multibuffers](https://zed.dev/docs/multibuffers). When doing a project-wide search that returns many Ruby files, that can also trigger this warning. I'm not sure if ruby-lsp should even be attempting semantic highlighting in that scenario. It's possible that's a separate problem that should have its own issue though.

**Comment by marknuzz** [comment]
@andyw8 I think there is actually a possible bug here. If you hold cmd to click to go to definition, then before clicking, hover over a definition that would have taken you to the file, the warning appears, even if you don't click or browse to that file. This is where the majority of the noise comes from, at least in my case. It's definitely quite distracting and I think that should be addressed separately.

 I don't think it needs to be notification in either case though, the output window seems fine.

**Comment by vinistock** [comment]
@marknuzz the aspect that you're referring to is likely because we're showing the notification on any type of URI instead of just the `file` scheme.

VS Code will open several other types of URIs when you are hovering or CMD + hover to display previews. Even Copilot chat has its own scheme for showing code snippets.

@alexcrocha as we discussed between the team, I think we should do the following:

1. Only log something if the scheme is `file`
2. Print to the output tab (use a window log message) instead of showing a dialog

To be frank I added the notification myself and got tired of it pretty quick 😅.
