### ISSUE TITLE
Add support for call hierarchies

### ISSUE THREAD

**Issue by kikeenrique** [Shopify/ruby-lsp#340]
Hi,
I develop in ruby from time to time, and I really miss the possibility to search for a function call hierarchy.
From ignorance, would it be feasible to add support for it?

Reference:
[LSP spec Call Hierarchy #468](https://github.com/Microsoft/language-server-protocol/issues/468)

**Comment by vinistock** [comment]
Hello!

I don't believe it would be possible to get the complete hierarchy without typechecking, given that it needs to find occurrences of method invocations across the entire codebase.

It might be possible to provide a best effort hierarchy that may not be super accurate, maybe just matching based on method names and argument counts. In order to explore it, we need to complete #199 first.
