### ISSUE TITLE
Formatting with both SyntaxTree and Rubocop installed doesn't work as expected

### ISSUE THREAD

**Issue by Petercopter** [Shopify/ruby-lsp#420]
I've been using both Rubocop and SyntaxTree for awhile. I just switched to using `ruby-lsp`. I'm using `vscode-ruby-lsp` with format on save.

```
  "[ruby]": {
    "editor.defaultFormatter": "Shopify.ruby-lsp"
  }
```

When Rubocop is present in the Gemfile, ruby-lsp formatting uses Rubocop. When I remove Rubocop from the Gemfile, it uses SyntaxTree. I would expect that Rubocop would format, then hand off to SyntaxTree, or vice versa, right?

```
ruby '3.2.0'

gem 'rails', '~> 7.0.4'
gem 'rubocop', '~> 1.2'
gem 'ruby-lsp', git: 'https://github.com/Shopify/ruby-lsp', require: false
gem 'syntax_tree', '~> 5.0'
gem 'syntax_tree-haml', '~> 3.0'
```

.rubocop.yml
```
inherit_gem:
  syntax_tree: config/rubocop.yml
```

**Comment by andyw8** [comment]
I think we need to update the documentation regardless, currently https://shopify.github.io/ruby-lsp/RubyLsp/Requests/Formatting.html only mentions RuboCop. I've created https://github.com/Shopify/ruby-lsp/issues/440.

**Comment by andyw8** [comment]
Relatedly, if we were to implement https://github.com/Shopify/ruby-lsp/issues/432 then would it make sense to have SyntaxTree as an option?

**Comment by molawson** [comment]
I'd be very interested in this ability to run RuboCop and SyntaxTree as formatters for the same reasons as @Petercopter laid out.  

My company has both tools in many of our repos.  While there are some conflicts, we've had success following the instructions in the SyntaxTree readme (i.e. disabling RuboCop rules that SyntaxTree will format away), as well as running SyntaxTree _after_ any RuboCop fixes.  

SyntaxTree tends to be more opinionated (in a good way) than RuboCop's autoformatter, but there are still a class of autocorrect-able offenses that SyntaxTree doesn't handle at all.  So only relying on SyntaxTree means that we've got to fix all RuboCop offenses manually or have a separate process or plugin that will do the RuboCop pass.  Having those in the same LSP so they could be given relative precedence, would be really nice.

I absolutely expect this to slow things down a bit locally because we're doing two formatting passes.  But it's still faster–and requires less thinking–than having to do one step manually, representing a nice QoL improvement compared to our current setup.
