### ISSUE TITLE
Unexpected formatting behaviour in Gemfile

### ISSUE THREAD

**Issue by larouxn** [Shopify/ruby-lsp#571]
⚠️ Not sure if this is expected behavior for `ruby-lsp` or not.

Seems `ruby-lsp` does not style Gemfile according to RuboCop config despite working fine on pure `.rb` files. 🤔 

https://user-images.githubusercontent.com/1557529/227085530-a68d405d-cca0-43c5-bcb8-6c042ba7653a.mov

I would expect Gemfile and `.rb` files to be formatted similarly via `ruby-lsp`.

**Comment by vinistock** [comment]
This works fine for me, so I think this has potential to be an issue in configuration. When you open the `Gemfile`, what language mode do you see? That is, does it say `Ruby` at the bottom right of VS Code or does it say something else such as `Gemfile`?

If it says anything other than Ruby, then you likely have another extension registering the `Gemfile` to a different language mode. In that case, the Ruby LSP is not even picking up that file, because it only processes files that are using the Ruby language mode. The fact that you're still getting formatting probably means you have another extension providing RuboCop formatting.

Please try the following
- Check the language mode for the Gemfile
- Check if you have other RuboCop related extensions installed. You don't need anything other than the Ruby LSP to get RuboCop formatting
- Check if you have any other extensions that might be registering the Gemfile to a different language mode

**Comment by larouxn** [comment]
👋 Hey @vinistock, thanks for the instructions. Indeed, Gemfile was being treated as "Gemfile" instead of "Ruby". Switching it to "Ruby" formatting works perfectly fine. 🙌

**Comment by vinistock** [comment]
Glad it worked out! If I can make a recommendation, uninstalling whatever other extensions are providing formatting or changing the language mode in the Gemfile will probably enhance your experience. Cheers!
