### ISSUE TITLE
Need configuration to ignore certain linter rules from autocorrection

### ISSUE THREAD

**Issue by paracycle** [Shopify/ruby-lsp#596]
There are cases when doing development that one legitimately needs to use a construct that is not wanted in production. For example, one might want to add a breakpoint in the code using `binding.b` or focus on a test by adding the `focus` keyword on it. Both of these are valid use-cases during development, but are linting errors, and are thus flagged, or, even worse, removed from code completely.

For these cases, it would be good to have a default and/or user configurable set of linter rules for which we show diagnostics at information level (despite what the original rule says the level should be) and to ignore these rules when doing "Format on Save".

The ones that immediately jump to mind are:
- `RSpec/Focus` - has an autocorrect that [removes the `focus` keyword from tests marked with it](https://www.reddit.com/r/ruby/comments/124vb7i/comment/je47d6w/?utm_source=reddit&utm_medium=web2x&context=3)
- `Lint/Debugger` - does not autocorrect but adds a diagnostic with level `Warning`.

  ![image](https://user-images.githubusercontent.com/224488/228538187-9a1f32ab-b64e-4817-a68d-2a7006356bd2.png)

**Comment by andyw8** [comment]
> For the autocorrect part, the rule/cop shouldn't provide an autocorrect.

I agree, and I think there would be a good chance of having this behaviour changed if we open an issue in rubocop-rspec.

**Comment by bessey** [comment]
You can disable this functionality on a per cop basis:
```
RSpec/Focus:
  AutoCorrect: false
```

(I was about to open the rubocop-rspec issue myself, but found someone had raised this already https://github.com/rubocop/rubocop-rspec/pull/1212)

**Comment by bessey** [comment]
Though I note this is undocumented, at least [where I would expect it to be document in Rubocop's docs](https://docs.rubocop.org/rubocop/usage/auto_correct.html). So maybe an issue is still merited.

**Comment by nevans** [comment]
> For the autocorrect part, the rule/cop shouldn't provide an autocorrect

I respectfully disagree.  Rubocop's more aggressive autocorrects are incredibly useful.  The "unsafe" autocorrections don't run by default, and I agree that this particular autocorrection should be considered "safe".  But rubocop has many other safe autocorrections that I absolutely do _not_ want to run every time I save the file.

Fortunately, rubocop _already_ provides the ability to only run safe formatting auto-corrections, instead of _all_ safe auto-corrections: the `-x` (or `--fix-layout`) option.  As an added benefit, it's much faster than running all autocorrections.

IMO: https://github.com/Shopify/ruby-lsp/blob/6d63b6e55ed44df8ca869164a7a770a72ae17418/lib/ruby_lsp/requests/support/rubocop_formatting_runner.rb#L20 should be changed to use `-x` instead of `-a`.
