### ISSUE TITLE
Formatting error: uninitialized constant RubyLsp::Requests::Support::RuboCopFormattingRunner

### ISSUE THREAD

**Issue by numbcoder** [Shopify/ruby-lsp#601]
VScode config:
```json
{
    "rubyLsp.enableExperimentalFeatures": true,
    "rubyLsp.enabledFeatures": {
        "codeActions": true,
        "diagnostics": true,
        "documentHighlights": true,
        "documentLink": true,
        "documentSymbols": true,
        "foldingRanges": true,
        "formatting": true,
        "hover": true,
        "inlayHint": true,
        "onTypeFormatting": true,
        "selectionRanges": true,
        "semanticHighlighting": true,
        "completion": true
    },
    "rubyLsp.rubyVersionManager": "rbenv",
    "rubyLsp.formatter": "rubocop",
}
```
Rubocop has been installed.
```shell
$ ruby --version
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]

$ gem list | grep rubocop
rubocop (1.48.1)
rubocop-ast (1.28.0)
rubocop-performance (1.16.0)
rubocop-rails (2.18.0)
rubocop-thread_safety (0.5.0)

$ gem list | grep ruby-lsp
ruby-lsp (0.4.3)
```

When I format a Ruby file in VScode, an error message notifications pops up: 
> Formatting error: uninitialized constant RubyLsp::Requests::Support::RuboCopFormattingRunner

**Comment by numbcoder** [comment]
> This should definitely be working. If you check the language status centre (the curly braces next to the language mode Ruby), did the extension pick up the correct Ruby version?
<img width="389" alt="Screenshot 2023-04-01 at 14 39 15" src="https://user-images.githubusercontent.com/281076/229270080-8333dc6a-132d-4634-ae94-8cfa2d5774a6.png">


> Also, is RuboCop in your Gemfile? What does `bundle show rubocop` output?

No. In the Troubleshooting section of the vscode-ruby-lsp documentation, it is mentioned that if using v0.2.0 of this extension or above, it is necessary to double-check that the ruby-lsp gem is not present in the project's main Gemfile. Therefore, both ruby-lsp and rubocop are not present in my Gemfile.

**Comment by EvgenyAfanasev** [comment]
<img width="289" alt="Screenshot 2023-04-03 at 11 28 48" src="https://user-images.githubusercontent.com/98059020/229454579-4f0864a5-6064-456d-a844-5a903afefc32.png">
<img width="406" alt="Screenshot 2023-04-03 at 11 30 40" src="https://user
<img width="778" alt="Screenshot 2023-04-03 at 11 31 47" src="https://user-images.githubusercontent.com/98059020/229455279-008b2c09-22e2-4add-84c6-f640a4ede635.png">
-images.githubusercontent.com/98059020/229454992-2769dca3-9131-4a42-a39e-02c0617ac65b.png">

Also, settings from my settings.json isn't sync with ruby-lsp gui settings

**Comment by numbcoder** [comment]
@vinistock Thanks for your response.
Is there any plan to support RuboCop not in Gemfile? For some special reasons, we are not able to bundle the RuboCop to project's Gemfile

**Comment by vinistock** [comment]
We're adding support for a pointing the LSP to a [separate Gemfile](https://github.com/Shopify/vscode-ruby-lsp/pull/520), in which you could include RuboCop without adding it to your project.

However, I should point out that there's a lot of potential for inconsistency if developers on your team are using different versions of RuboCop - since different versions may have different behaviour. The best way to guarantee that the functionality in the editor matches for all devs and CI is to add it to the bundle.

**Comment by lucashungaro** [comment]
Hi everyone! Sorry for semi-necroing the thread, but I'm having some trouble finding help.

I'm running VSCode on Windows 11, connecting to Linux (WSL), where I have a Rails app running inside Docker. I've installed the ruby-lsp extension but formatting/linting is giving me the same error mentioned in this thread (installing the extension did not create a `.ruby-lsp` directory anywhere I could find). 

I see the "Ruby LSP is ready" message and the language status centre reports everything fine.

However, the ruby-lsp gem is installed on Linux, not in the Docker image, so I assume that's the issue. My options appear to be:

- Install ruby-lsp, rubocop, and other gems needed in the image (I wonder if the Docker VSCode extensions would help me with this);
- Add ruby-lsp to the project's Gemfile, so it gets installed inside the image, but this doesn't appear to be the way to do it anymore.

I'm open to suggestions and appreciate any help. Thank you so much!

**Comment by vinistock** [comment]
Hey, Lucas! Have you tried the official remote extension I mentioned in https://github.com/Shopify/vscode-ruby-lsp/issues/488#issuecomment-1498160047?

My understanding is that the extension allows you to connect to remote machines or containers and then VS Code runs extensions seamlessly as if they were inside the container.

**Comment by lucashungaro** [comment]
> Hey, Lucas! Have you tried the official remote extension I mentioned in [Shopify/vscode-ruby-lsp#488 (comment)](https://github.com/Shopify/vscode-ruby-lsp/issues/488#issuecomment-1498160047)?
> 
> My understanding is that the extension allows you to connect to remote machines or containers and then VS Code runs extensions seamlessly as if they were inside the container.

Not exactly that one, but it gave me an idea, so I used the Dev Containers extensions to actually connect to the Docker container and edit the code in there. I was able to install Ruby LSP, but now I hit the same error described here: https://github.com/Shopify/vscode-ruby-lsp/issues/536 (because our Docker config uses a custom bundler path).

I'm guessing my best option is to point to a custom Gemfile and just do my best to keep versions and settings in sync with the main repo. Using Dev Containers also has a downside since we have separate containers for the Rails API and the React front-ends, and it seems I can only be connected to one at a time, so editing files across projects (we have a monorepo) gets a bit cumbersome.
