### ISSUE TITLE
Rspec Syntax Support

### ISSUE THREAD

**Issue by TTiger** [Shopify/ruby-lsp#621]
Can you please add rspec support for syntax highlighting and outline veiw?

I see your grammar files are converted from Atom so I tracked one down here:
https://github.com/pauldruziak/language-rspec

**Comment by vinistock** [comment]
The Ruby LSP supports minitest and test-unit by default. Other gems will be able to enhance the Ruby LSP's functionality through the server extensions system #443. When the extension system is ready, people can create an RSpec extension to provide functionality for it.

That said, I should also point out that the file outline is not intended to surface tests (and tests are not included in the list of possible symbols). The fact that it appears for Minitest / test-unit is an accident because tests are defined using method definitions. We are surfacing method definitions and not tests.

The correct way to surface available tests to the editor is to use code lenses (#584) to populate a test explorer (https://github.com/Shopify/vscode-ruby-lsp/issues/498).

When those two test related issues are complete and when the extension system is in placed, the correct way to go about this would be to create an RSpec Ruby LSP extension and
- Add a semantic highlighting listener to enhance the base highlighting
- Add a code lens listener to find RSpec test examples to populate the test explorer

Once we finish #443, there will be more documentation on how to go about creating an extension.
