### ISSUE TITLE
LSP not working correctly for unsaved/temporary files in VSCode

### ISSUE THREAD

**Issue by tepsukka** [Shopify/ruby-lsp#633]
If I create a new ruby file without saving it in VSCode, the file is not being run through LSP even though it is activated, as you can see in the images below: 

![saved_file](https://user-images.githubusercontent.com/38805997/231679017-afe60a29-469b-4260-96a7-c36683c1b3bc.png)
![unsaved_file](https://user-images.githubusercontent.com/38805997/231679024-91acfbf1-81b2-4377-96b7-94eeed1dbace.png)

You can observe a similar behavior when using VSCode to compare file changes.

Information about my environment:

- Ruby LSP v0.2.4
- ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
- Rails 7.0.4.2
- Using rbenv as version manager, the project has a bundle.
- Debian GNU/Linux 11

**Comment by vinistock** [comment]
For anyone who ends up looking into this: I would start by verifying if we are receiving `textDocument/didOpen` notifications when these temporary files are created.

It's likely we don't receive it because when you create a temporary file, the language mode is set to plain text. I don't know if we should receive a notification when the language mode is changed to Ruby.

I would check to see if LSPs are supposed to receive some notification when the language mode is changed and how we should handle that.

**Comment by paracycle** [comment]
I looked into this issue and found that it stems from us registering the LSP client specifically for files on disk, as explained here: https://code.visualstudio.com/api/references/document-selector

If we change our registration from `documentSelector: [{ scheme: "file", language: "ruby" }]` to `documentSelector: [{ language: "ruby" }]` or to `documentSelector: [{ scheme: "file", language: "ruby" }, { scheme: "untitled", language: "ruby" }]`, this case immediately starts working. However, the URI of the file is sent as something like `untitled:Untitled-1`, so we need to be careful when parsing URI on the `ruby-lsp` side.

**Comment by vinistock** [comment]
Thinking more about this problem, I think `Document` needs to start storing a `URI` instance rather than a string.

And when we process requests in `Executor`, we should always parse the uri with `URI(uri)` and send the actual object to all requests.
