### ISSUE TITLE
Support specifying a custom bundler group to install from Gemfile

### ISSUE THREAD

**Issue by TSMMark** [Shopify/ruby-lsp#662]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

I have a lot of gems in my gemfile. Only like 5% of them are actually needed to ruby Ruby LSP in VS Code. E.g. rubocop, rubocop-minitest, rubocop-performance, rubocop-graphql

### Description

I have the necessary gems in a bundler group

```
group :test, :vscode do
```

I'd like to be able to tell Ruby-LSP to only install the vscode group. 

```
Bundler.require(:vscode)
```

### Implementation

When ruby-lsp installs gems in `.ruby-lsp/gemfile`, it could install only the configured group, e.g.:

```
BUNDLE_WITH="vscode" bundle install
```

**Comment by TSMMark** [comment]
Would maintainers accept a PR for this?

**Comment by TSMMark** [comment]
Nice! A custom activation to specify `BUNDLE_WITH` would be perfect actually. Looking forward to the merge and release of https://github.com/Shopify/vscode-ruby-lsp/pull/583

Feel free to tag me on it if you want some testers eventually

**Comment by vinistock** [comment]
Hello!

I don't think the Ruby LSP should be concerned with Gemfile groups in any way. If a gem can't be installed in all platforms, then I believe the solution is to scope to the platforms where it can be installed.

For example, Sorbet doesn't support Windows and so we [scope it to all other platforms](https://github.com/Shopify/ruby-lsp/blob/3e6b20fcf21cbb7254758b1d9b68ec76ff53c0f7/Gemfile#L22). In your case, you'd need to scope it to platforms that do not include Darwin ARM.

I also don't understand how you don't have the same issue when running `bundle install` in your terminal - since that's all the LSP is doing. Are you running bundle install with some configuration when you do it manually?

**Comment by jfahrenkrug** [comment]
Hello and thank you for your helpful reply.

I'll answer your second question first: I ran `bundle config set --local without 'production'` before running `bundle install`. It works fine. But I don't think ruby-lsp takes that config setting into account. That would actually be nice if it did.

Thank you for your suggestion about the `platform` setting in the Gemfile. I'll have to try that. There's no obvious "non-mac-os" platform that would also include Ubuntu, so I'll have to do some experimenting. If you happen to know what I'd have to specify to get "every Unix platform except for macOS (or macOS ARM)".... :) Thanks!

**Comment by vinistock** [comment]
I'm sorry, you were correct and I was misunderstanding the issue. The Bundler app config path is pointing to the wrong directory because we set `BUNDLE_GEMFILE` for the custom bundle.

This PR should fix it https://github.com/Shopify/ruby-lsp/pull/1093.

**Comment by jfahrenkrug** [comment]
@vinistock Thanks so much! Looking forward to the next release that will contain this fix. Thanks again!
