### ISSUE TITLE
Stuck at the "Fetching Rails Documents..." step

### ISSUE THREAD

**Issue by kotepillar** [Shopify/ruby-lsp#669]
### Ruby version

ruby 3.2.1p31

### Description

>> `bundle install` exited with code 0
Starting Ruby LSP...
Ruby LSP is ready
Fetching Rails Documents... # Stuck here, vscode hovering over the variable and it keeps showing 'loading'

RUBY VERSION
   ruby 3.2.1p31
BUNDLED WITH
   2.4.6

### Expected output

VSCode can correctly display hints

**Comment by kotepillar** [comment]
> Does the `loading` message never go away? 
The loading prompt only appears for a few seconds.
> And is there anything else in the output tab?
There is no other output.

Additional information:
rails (7.0.4.3)
Operating System: macOS

**Comment by andyw8** [comment]
I suspect this is a networking issue.

Ae you able to access https://api.rubyonrails.org/ through your browser?

Does your connection go through a proxy server?

**Comment by vinistock** [comment]
I think there are two things mixed here.

1. The LSP indeed only prints `Fetching Rails Documents...`. It does not print `Finished fetching Rails documents` or anything like that. However, it does not mean that it's stuck - even if fetching fails it just continues to serve other features normally
2. The second part is the expectation of certain features. We have not yet finished implementing autocomplete or go to definition, which is why they aren't present. You can see the list of supported features in our [documentation](https://shopify.github.io/ruby-lsp/RubyLsp/Requests.html)

I'm closing this for now. Please report back if the LSP is indeed stuck.

**Comment by jlahtinen** [comment]
I am behind corporate proxy. I use remote development using SSH. I am able to download extensions through proxy because vscode ui knows about my corporate proxy same way as chrome does. All extension downloading happens from the machine vscode ui is operated.

ruby-lsp language server, running on remote ssh machine communicating with lsp with vscode on machine where proxy settings are set, cannot connect internet through proxy and `Fetching Rails Documents....` hangs. 

If I understand correctly Net::HTTP (this is used to create http requests) automatically uses http_proxy environment when set. But unfortunately http_proxy is not set when ruby-lsp language server process starts (or maybe more precisely: when Visual Studio Code Server starts on remote machine).

Is there any other way to tackle this but make sure http_proxy is set then Visual Studio Code Server starts? Could ruby-lsp connect to internet through lsp (there operating vscode machine knows about proxy - i do now know if there is an API for this)? Could all resources needed from the internet be packed to another extension and ruby-lsp be dependent of them? Could ruby-lsp extension contain all resources? Any other way?

I think that minimum info about this (if http_proxy is only way) should be on the README. Something like: "with remote ssh development behind proxy. make sure you have http_proxy environment variable set on the environment where Visual Studio Code Server is running". Maybe some link to documentation how this (setting env variables for vscode server) can be done.
