### ISSUE TITLE
Won't report Lint/Syntax for some kind of Syntax errors

### ISSUE THREAD

**Issue by andreacasarin** [Shopify/ruby-lsp#696]
### Ruby version

2.7.6

### Code snippet

![Screenshot 2023-05-04 at 16 54 16](https://user-images.githubusercontent.com/10467381/236259882-61f8e7fa-c525-4390-8a52-3c8751d13097.jpg)
![Screenshot 2023-05-04 at 16 54 27](https://user-images.githubusercontent.com/10467381/236259895-17dadd87-21e0-4391-b111-f7bb24ac890f.jpg)
![Screenshot 2023-05-04 at 16 55 12](https://user-images.githubusercontent.com/10467381/236259907-5a99d5c6-7530-42fb-8bc9-c32c28bbd1be.jpg)

### Description

Hello, first of all thanks for the great work, I've been experimenting with it for some time and it's super fast and useful.

While testing I've encountered some weird case in which the LS doesn't report a syntax error, even if it's reported by rubocop. I've attached a few screenshots, as you can see some errors are reported, others are not and the file is not parsed at all, however when running rubocop it reports all errors.

I might be doing something wrong on my side but I'm not sure where. 

### Expected output

I'd expect to receive a syntax error for every relevant code.

**Comment by andyw8** [comment]
Hi @andreacasarin,

Thanks for the report. We use Syntax Tree for parsing, and if the document can't be parsed, then currently we don't send it to RuboCop:

https://github.com/Shopify/ruby-lsp/blob/55e1a728ecec80903d39322c6a1202fdb0fff312/lib/ruby_lsp/requests/diagnostics.rb#L33

We _may_ be able to change this, but we'd need to look into how RuboCop handles files with very broken syntax.

**Comment by vinistock** [comment]
This is by design. Unfortunately, running RuboCop related tasks are by very far the slowest things we do in the LSP.

We try to optimize the number of times we execute RuboCop diagnostics by not running it while there's a syntax error.

Once we're able to migrate to the new parser [YARP](https://github.com/Shopify/yarp), we will take advantage of the built-in error tolerance to display syntax errors without relying on RuboCop, which will improve the experience while maintaining the performance.
