### ISSUE TITLE
Usage without a Gemfile

### ISSUE THREAD

**Issue by boris-petrov** [Shopify/ruby-lsp#708]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

I am using Ruby via JRuby and I'm using Gradle as a build system and the [JRuby Gradle Plugin](https://github.com/jruby-gradle/jruby-gradle-plugin) to install gems and use them. I want to get 1) RuboCop warnings in VSCode (most importantly) and perhaps 2) all the other nice features of `ruby-lsp`. However, it seems that it requires a Gemfile for most of its functionality. The `JRuby Gradle Plugin` doesn't work with a Gemfile but with custom Gradle syntax.

### Description

Some way of letting `ruby-lsp` what my gems are without them being in a Gemfile. It would also be nice to not have to duplicate that information between my Gradle file and some other place (be it a Gemfile).

**Comment by mateusdeap** [comment]
I'm sorry, not sure if my comment is useful to the issue at hand, but I just wanted to confirm that this corresponds to what I encountered.

Basically, I recently tried to setup a project with `ruby-lsp` and, while it did have a Gemfile, I had not yet run `bundle install`, so when I tried to run `ruby-lsp` I would get this error:
![image](https://github.com/Shopify/ruby-lsp/assets/14188887/9cd16397-a1b4-42ec-bb82-1440c8d047ec)

Does this correspond to this feature request? I mean, the project does have a Gemfile, but I'm kind of assuming that the error is due to some expectation or requirement that we at least work with Gemfiles. Because, otherwise, I wanted to open an issue with this exception to see if there's a fix or not.

**Comment by boris-petrov** [comment]
No, this isn't what I mean. I meant to be able to use `ruby-lsp` **without** a `Gemfile` file at all.

**Comment by e1senh0rn** [comment]
My scenario is close to what @halilim described: I have bunch of ad-hoc scripts here and there. They are self-contained though: I use `bundler/inline` to handle dependencies transparently:
```
#!/usr/bin/env ruby

require 'rubygems'

require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'slop'
end

# ...
```

**Comment by vinistock** [comment]
Okay, I created https://github.com/Shopify/ruby-lsp/pull/2155 to warn users about the current lack of support for no workspaces at the moment.

Regarding the original issue, I'm going to close it for now. We rely heavily on Bundler to figure out which dependencies should be indexed, for setting up the custom bundle, for connecting directly to the project's linter and formatter and so on.

Unless Gradle can somehow connect with Bundler or provide equivalent APIs, I don't think it will be possible to support it. We would need someone interested in Gradle support to investigate, provide more detailed information about how to integrate with it and then take a stab at making our dependency on Bundler be pluggable.

It would be a considerable effort and would likely require some sort of abstraction layer between the LSP and the dependency manager, so that each manager can do the right thing.

```ruby
class DependencyManagement
  def bundled_gems
    # return specification objects for bundled gems
    # so that we can find them in the file system
  end

  def default_gems
    # return specification objects for default gems
    # so that we can find them in the file system
  end

  def default_dependency_file
    # return the name of the file that controls dependencies (default being Gemfile)
  end

  def install_dependencies
    # install dependencies (e.g.: bundle install for Bundler)
  end

  def update_dependencies(names)
    # ...
  end
end
```
