### ISSUE TITLE
Handle unicode uppercase characters in autocomplete

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#990]
See https://github.com/Shopify/ruby-lsp/pull/957#discussion_r1310779085 for more context.

We currently only support `"A".."Z"` for completion. Let's understand the efforts and trade offs for supporting any arbitrary uppercase unicode character for completion, since Ruby does allow them to be used in constant names.

**Comment by kddnewton** [comment]
The characters that can begin constants depends on the source encoding. If it's `# encoding: ascii` then what you have is correct. So whatever solution you end up with, you should use the encoding of the source file.

A cheap way to do it is to ask Ripper or YARP. Both will have the encoding object for you.

```ruby
encoding = Ripper.new(source).tap(&:parse).encoding
```

Once you have the encoding, you should make a regexp that is fixed so that encoding:

```ruby
regexp = Regexp.new("[[:upper:]]".encode(encoding), Regexp::FIXEDENCODING)
```

then you can check if it matches the character:

```ruby
begin
  regexp.match?(character)
rescue Encoding::CompatibilityError
  # If the character can't be represented in that encoding, then
  # it can't possibly be uppercase.
  false
end
```

**Comment by kddnewton** [comment]
@nirvdrum would know much more about this

**Comment by vinistock** [comment]
@paracycle found out the right answer in https://github.com/Shopify/ruby-lsp/pull/1171#discussion_r1386765023. The spec already handles any valid identifier for trigger characters, so we actually don't have to worry about this.

Just indexing constants that use unicode characters should be enough.

**Comment by vinistock** [comment]
Honestly, this doesn't feel like it's worth the effort and we received no requests for supporting this.
